import { useEffect, useMemo, useRef, useState } from "react";
import { Breadcrumb, EcdatHeader } from "@/components/EcdatHeader";
import { WorkspaceState } from "@/components/WorkspaceState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useActiveEcdatScan } from "@/hooks/useActiveEcdatScan";
import { buildEvidenceGraphLayout } from "@/lib/explorationUtils";
import { buildSpatialGraph, cleanSpatialLabel, spatialNodeKind } from "@/lib/spatialProjection";
import { Crosshair, GitBranch, Move, Network, RotateCcw, ZoomIn, ZoomOut } from "lucide-react";

const nodeColors: Record<string, string> = { service: "#67e8f9", endpoint: "#a5f3fc", asset: "#fbbf24", algorithm: "#fb7185", library: "#a78bfa", certificate: "#34d399", "certificate-authority": "#2dd4bf", data: "#60a5fa" };

export default function Graph() {
  const workspace = useActiveEcdatScan();
  const { relationships, findings } = workspace;
  const requestedFinding = useMemo(() => new URLSearchParams(window.location.search).get("finding"), []);
  const [selected, setSelected] = useState<string | null>(null);
  const [viewport, setViewport] = useState({ x: 0, y: 0, scale: 1 });
  const dragOrigin = useRef<{ x: number; y: number; viewportX: number; viewportY: number } | null>(null);
  const graphNodes = useMemo(() => buildSpatialGraph(relationships, findings), [relationships, findings]);
  useEffect(() => {
    if (!requestedFinding) return;
    const target = graphNodes.find(node => node.findingKeys.includes(requestedFinding));
    if (target) setSelected(target.id);
  }, [graphNodes, requestedFinding]);
  const positioned = useMemo(() => buildEvidenceGraphLayout(graphNodes.map(node => ({ id: node.id, kind: node.kind }))), [graphNodes]);
  const positionById = useMemo(() => new Map(positioned.map(node => [node.id, node])), [positioned]);
  const focusedNode = selected ?? graphNodes[0]?.id;
  const activeEdges = relationships.filter(edge => edge.sourceNode === focusedNode || edge.targetNode === focusedNode);
  const affectedNodes = new Set(activeEdges.flatMap(edge => [edge.sourceNode, edge.targetNode]));
  const focusedGraphNode = graphNodes.find(node => node.id === focusedNode);
  const relatedFindings = findings.filter(finding => focusedGraphNode?.findingKeys.includes(finding.findingKey));
  const severity = relatedFindings.reduce<Record<string, number>>((counts, finding) => { counts[finding.riskLevel] = (counts[finding.riskLevel] ?? 0) + 1; return counts; }, {});
  const nodeTypes = Array.from(new Set(graphNodes.map(node => node.kind))).sort();

  if (workspace.hasError) return <WorkspaceState state="error" title="Dependency graph is unavailable" description="The current relationship evidence could not be retrieved." onRetry={() => void workspace.retry()} />;
  if (workspace.isLoading && !relationships.length) return <WorkspaceState state="loading" title="Building the dependency graph" description="Connecting observed services, cryptographic assets, and evidence paths." />;
  if (!relationships.length) return <WorkspaceState state="empty" title="No relationship evidence yet" description="Run a seeded scan to populate the service, library, algorithm, certificate, endpoint, and data graph." />;

  const resetViewport = () => setViewport({ x: 0, y: 0, scale: 1 });
  const adjustZoom = (amount: number) => setViewport(current => ({ ...current, scale: Math.max(0.6, Math.min(1.8, Number((current.scale + amount).toFixed(2)))) }));

  return <div className="mx-auto max-w-[1550px]"><Breadcrumb section="Dependency graph" /><EcdatHeader eyebrow="Dependency intelligence" title="See the path behind the risk." description="Nodes are grounded in scanner evidence. Follow shared libraries, crypto primitives, certificates, endpoints, and protected data into a remediation sequence." />
    <div className="mt-7 grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><section className="relative min-h-[650px] overflow-hidden rounded-3xl border border-white/8 bg-[radial-gradient(circle_at_50%_10%,rgba(34,211,238,0.09),transparent_37%),#091423] p-5"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(148,163,184,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.08)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="relative flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-100"><Network className="h-4 w-4" /></span><div><p className="text-sm font-medium text-slate-100">Evidence graph</p><p className="text-xs text-slate-500">Type-aware layout from active relationship evidence · select a node to focus paths</p></div></div><div className="flex items-center gap-2"><Badge variant="outline" className="border-white/10 text-slate-400">{graphNodes.length} nodes · {relationships.length} edges</Badge><Button size="icon" variant="outline" aria-label="Zoom graph in" onClick={() => adjustZoom(0.15)} className="border-white/10 bg-[#06101c] text-slate-300"><ZoomIn className="h-4 w-4" /></Button><Button size="icon" variant="outline" aria-label="Zoom graph out" onClick={() => adjustZoom(-0.15)} className="border-white/10 bg-[#06101c] text-slate-300"><ZoomOut className="h-4 w-4" /></Button><Button size="icon" variant="outline" aria-label="Reset graph view" onClick={resetViewport} className="border-white/10 bg-[#06101c] text-slate-300"><RotateCcw className="h-4 w-4" /></Button></div></div>
      <svg className="relative mt-6 h-[430px] w-full touch-none" viewBox="0 0 960 600" preserveAspectRatio="xMidYMid meet" onWheel={event => { event.preventDefault(); adjustZoom(event.deltaY < 0 ? 0.1 : -0.1); }} onPointerDown={event => { dragOrigin.current = { x: event.clientX, y: event.clientY, viewportX: viewport.x, viewportY: viewport.y }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { const origin = dragOrigin.current; if (!origin) return; setViewport(current => ({ ...current, x: origin.viewportX + (event.clientX - origin.x) / current.scale, y: origin.viewportY + (event.clientY - origin.y) / current.scale })); }} onPointerUp={() => { dragOrigin.current = null; }}><g transform={`translate(${viewport.x} ${viewport.y}) scale(${viewport.scale})`}>{relationships.map((edge, index) => { const source = positionById.get(edge.sourceNode); const target = positionById.get(edge.targetNode); if (!source || !target) return null; const active = edge.sourceNode === focusedNode || edge.targetNode === focusedNode; return <line key={`${edge.sourceNode}-${edge.targetNode}-${index}`} x1={source.x} y1={source.y} x2={target.x} y2={target.y} stroke={active ? "#f0b428" : "#3d5588"} strokeWidth={active ? 3 : 1.3} strokeOpacity={active ? 0.9 : 0.35} />; })}{graphNodes.map(node => { const position = positionById.get(node.id); if (!position) return null; return <GraphNode key={node.id} x={position.x} y={position.y} node={node} active={node.id === focusedNode} affected={affectedNodes.has(node.id)} onClick={() => setSelected(node.id)} />; })}</g></svg><div className="relative mt-1 flex flex-wrap items-center gap-2"><Move className="h-3.5 w-3.5 text-slate-600" /><span className="text-[10px] text-slate-500">Drag to pan · scroll or controls to zoom</span>{nodeTypes.map(type => <span key={type} className="inline-flex items-center gap-1.5 rounded-md border border-white/10 bg-white/[0.035] px-2 py-1 text-[10px] text-slate-400"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: nodeColors[type] ?? "#94a3b8" }} />{type}</span>)}</div></section>
      <aside className="rounded-3xl border border-white/8 bg-[#091423] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-300/10 text-violet-100"><Crosshair className="h-4 w-4" /></span><div><p className="text-sm font-medium text-slate-100">Blast-radius lens</p><p className="text-xs text-slate-500">Observed relationship path</p></div></div><div className="mt-6 rounded-2xl border border-white/7 bg-[#06101c]/70 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-600">Focused node</p><p className="mt-2 break-words font-display text-lg text-white">{cleanSpatialLabel(focusedNode ?? "No node selected")}</p><p className="mt-3 text-xs leading-5 text-slate-400">{affectedNodes.size} affected observed entities · {activeEdges.length} direct evidence-backed relationship{activeEdges.length === 1 ? "" : "s"}.</p></div><div className="mt-4 grid grid-cols-4 gap-2">{["Critical", "High", "Medium", "Low"].map(level => <div key={level} className="rounded-lg border border-white/7 bg-white/[0.025] p-2 text-center"><p className="font-display text-sm text-white">{severity[level] ?? 0}</p><p className="mt-1 text-[9px] uppercase tracking-wider text-slate-600">{level}</p></div>)}</div><div className="mt-5 space-y-2">{activeEdges.slice(0, 6).map((edge, index) => <div key={`${edge.sourceNode}-${edge.targetNode}-${index}`} className="rounded-xl border border-white/7 bg-white/[0.025] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-cyan-200/65">{edge.relationship}</p><p className="mt-1 text-xs text-slate-300">{cleanSpatialLabel(edge.sourceNode)} <span className="text-slate-600">→</span> {cleanSpatialLabel(edge.targetNode)}</p><p className="mt-1.5 text-[11px] leading-4 text-slate-600">{edge.evidence}</p></div>)}</div><div className="mt-5 rounded-xl border border-amber-200/10 bg-amber-200/[0.035] p-3 text-xs leading-5 text-amber-100/85"><GitBranch className="mr-1.5 inline h-3.5 w-3.5" />Shared dependency impact is a prioritisation signal, not proof of runtime reachability.</div></aside></div></div>;
}

function GraphNode({ x, y, node, active, affected, onClick }: { x: number; y: number; node: { id: string; label: string; kind: string }; active: boolean; affected: boolean; onClick: () => void }) { const color = nodeColors[node.kind] ?? "#94a3b8"; return <g transform={`translate(${x - 80} ${y - 30})`} onClick={event => { event.stopPropagation(); onClick(); }} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onClick(); } }} tabIndex={0} role="button" aria-label={`Focus ${node.label} dependency node`} className="cursor-pointer focus:outline-none"><rect rx="12" width="160" height="60" fill={active ? "#173049" : "#0b1b2d"} stroke={active ? "#f0b428" : affected ? color : "#334155"} strokeWidth={active ? 2.5 : affected ? 1.5 : 1} /><circle cx="15" cy="16" r="4" fill={color} /><text x="26" y="20" fill={color} fontSize="9" fontWeight="700" letterSpacing="1">{node.kind.toUpperCase()}</text><text x="14" y="43" fill="#e2e8f0" fontSize="11">{node.label.slice(0, 22)}</text></g>; }
