import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { EcdatHeader } from "@/components/EcdatHeader";
import { AlgorithmDistribution, QuantumExposureChart, RiskDistributionChart } from "@/components/CommandCenterCharts";
import { MetricCard } from "@/components/MetricCard";
import { ReadinessGauge } from "@/components/ReadinessGauge";
import { ScanProgress } from "@/components/ScanProgress";
import { WorkspaceState } from "@/components/WorkspaceState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { startLogin } from "@/const";
import { useActiveEcdatScan } from "@/hooks/useActiveEcdatScan";
import { buildCommandCenterViewModel } from "@/lib/commandCenter";
import { type ScenarioId } from "@/lib/ecdatUi";
import { postScanDestination } from "@/lib/scanCompletion";
import { type ScannerPhase } from "@/lib/scannerProgress";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowRight, BookOpenCheck, Boxes, CheckCircle2, GitBranch, LockKeyhole, Play, ScanSearch, ShieldAlert, Sparkles, TriangleAlert } from "lucide-react";
import { useLocation } from "wouter";

export default function Home() {
  const [scenario, setScenario] = useState<ScenarioId>("python-web");
  const [repositoryUrl, setRepositoryUrl] = useState("");
  const scannerQaState = useMemo(() => import.meta.env.DEV ? new URLSearchParams(window.location.search).get("qaState") : null, []);
  const [scannerPhase, setScannerPhase] = useState<ScannerPhase>(() => scannerQaState === "scanner-error" ? "error" : "idle");
  const [cataloguedAssets, setCataloguedAssets] = useState<number | undefined>();
  const { data: catalog = [] } = trpc.ecdat.scenarioCatalog.useQuery();
  const { error: intakeError, refetch: refetchIntake } = trpc.ecdat.preview.useQuery({ scenario });
  const active = useActiveEcdatScan();
  const { isAuthenticated, loading: authLoading } = useAuth();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const runDemo = trpc.ecdat.runDemo.useMutation({ onSuccess: async detail => { localStorage.setItem("ecdat-last-scan", detail.scan.scanKey); await utils.ecdat.scans.invalidate(); await utils.ecdat.detail.invalidate(); setCataloguedAssets(detail.scan.totalAssets); setScannerPhase("complete"); window.setTimeout(() => setLocation(postScanDestination()), 900); }, onError: () => setScannerPhase("error") });
  const scenarioInfo = catalog.find(item => item.id === scenario);
  const model = useMemo(() => buildCommandCenterViewModel({ displayName: active.displayName, totalAssets: active.totalAssets, quantumReadiness: active.quantumReadiness, findings: active.findings, recommendations: active.recommendations, relationships: active.relationships, usingSavedScan: active.usingSavedScan }, active.recentScans), [active.displayName, active.totalAssets, active.quantumReadiness, active.findings, active.recommendations, active.relationships, active.usingSavedScan, active.recentScans]);

  function selectScenario(next: ScenarioId) { setScenario(next); const target = catalog.find(item => item.id === next); if (target) setRepositoryUrl(target.repositoryPlaceholder); }
  function beginScan() { if (!isAuthenticated) return startLogin(); setCataloguedAssets(undefined); setScannerPhase("running"); runDemo.mutate({ scenario, repositoryUrl: repositoryUrl.trim() || undefined }); }
  const routeInventory = (query = "") => setLocation(`/inventory${query}`);

  if (active.hasError) return <div className="mx-auto max-w-[1550px]"><EcdatHeader eyebrow="Enterprise cryptographic discovery & analysis" title="Command Center" description="A single active-scan view of cryptographic evidence, planning exposure, and generated migration priorities." /><div className="mt-7"><WorkspaceState state="error" title="Command Center data is unavailable" description="The active scan could not be resolved. Retry to restore evidence-backed assessment and decision panels." onRetry={() => void active.retry()} /></div></div>;
  if (active.isLoading && !active.findings.length) return <div className="mx-auto max-w-[1550px]"><EcdatHeader eyebrow="Enterprise cryptographic discovery & analysis" title="Command Center" description="A single active-scan view of cryptographic evidence, planning exposure, and generated migration priorities." /><div className="mt-7"><WorkspaceState state="loading" title="Preparing the Command Center" description="Resolving the active scan’s evidence, generated recommendations, and planning context." /></div></div>;

  return <div className="observatory-command-center mx-auto max-w-[1550px] space-y-7">
    <EcdatHeader eyebrow="Enterprise cryptographic discovery & analysis" title="Command Center" description="A single active-scan view of cryptographic evidence, planning exposure, and generated migration priorities." />
    <section className="grid gap-5 xl:grid-cols-[0.72fr_1.28fr]">
      <div className="rounded-3xl border border-cyan-200/12 bg-[#0a1727] p-5 shadow-2xl shadow-black/15"><div className="flex items-center justify-between gap-3"><Badge className="gap-1.5 border border-cyan-200/20 bg-cyan-300/10 text-cyan-100"><Sparkles className="h-3.5 w-3.5" />Discovery intake</Badge><span className="text-[10px] font-medium uppercase tracking-[0.14em] text-slate-500">Seeded demo</span></div><p className="mt-4 text-sm font-medium text-slate-100">Start or save an evidence-backed scenario.</p><p className="mt-1 text-xs leading-5 text-slate-500">The demonstration stores a target and runs a deterministic scenario. It does not clone or process a private repository.</p>{intakeError ? <div role="alert" className="mt-4 flex items-center justify-between gap-3 rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-3 text-xs text-rose-100">Scenario data is unavailable.<Button size="sm" variant="outline" onClick={() => refetchIntake()} className="border-rose-200/20 bg-transparent text-rose-100">Retry</Button></div> : <><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><div className="relative"><GitBranch className="absolute left-3 top-3 h-4 w-4 text-slate-500" /><Input aria-label="Repository URL" value={repositoryUrl} onChange={event => setRepositoryUrl(event.target.value)} placeholder={scenarioInfo?.repositoryPlaceholder ?? "Repository target"} className="h-10 border-white/10 bg-[#06101c] pl-9 text-xs text-slate-100 placeholder:text-slate-600" /></div><Button onClick={beginScan} disabled={runDemo.isPending || authLoading || scannerPhase === "complete"} className="h-10 bg-cyan-200 px-4 font-semibold text-[#072033] hover:bg-cyan-100"><Play className="h-3.5 w-3.5 fill-current" />{runDemo.isPending ? "Scanning…" : isAuthenticated ? "Scan" : "Sign in"}</Button></div><div className="mt-3 grid grid-cols-2 gap-2">{catalog.map(item => <button type="button" key={item.id} onClick={() => selectScenario(item.id as ScenarioId)} disabled={scannerPhase === "running"} aria-pressed={scenario === item.id} className={`rounded-xl border px-3 py-2 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60 disabled:cursor-not-allowed disabled:opacity-60 ${scenario === item.id ? "border-cyan-200/35 bg-cyan-300/[0.08] text-cyan-50" : "border-white/[0.07] bg-white/[0.02] text-slate-400 hover:border-white/15"}`}><span className="block text-xs font-medium">{item.label}</span><span className="mt-1 block truncate text-[10px] text-slate-500">{item.badges.slice(0, 2).join(" · ")}</span></button>)}</div>{scannerPhase !== "idle" ? <ScanProgress phase={scannerPhase} target={repositoryUrl.trim() || scenarioInfo?.repositoryPlaceholder || "Deterministic ECDAT demonstration target"} totalAssets={cataloguedAssets} onRetry={beginScan} /> : null}</>}</div>
      <div className="relative overflow-hidden rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><div className="pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full bg-violet-400/[0.08] blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium text-slate-500">{model.assessment.source}</p><Badge variant="outline" className="border-emerald-200/15 bg-emerald-300/[0.05] text-emerald-100">{active.usingSavedScan ? "Saved" : "Preview"}</Badge></div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.04em] text-white">{model.assessment.displayName}</h2><p className="mt-2 max-w-lg text-xs leading-5 text-slate-500">Assessment counts are derived from the same active findings, relationships, and generated actions used across the workspace.</p><div className="mt-5 grid grid-cols-3 gap-3"><SummaryMetric value={model.assessment.findings} label="Findings" /><SummaryMetric value={model.assessment.actions} label="Actions" /><SummaryMetric value={model.assessment.evidence} label="Evidence" /></div>{model.assessment.hndlDetected ? <div className="mt-4 inline-flex items-center gap-2 rounded-xl border border-amber-200/15 bg-amber-200/[0.05] px-3 py-2 text-xs text-amber-100"><AlertTriangle className="h-3.5 w-3.5" />Potential HNDL signals under active planning inputs</div> : null}</div><ReadinessGauge value={model.assessment.readiness} /></div>{active.hasError ? <div role="alert" className="relative mt-5 rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-3 text-xs text-rose-100">Unable to refresh active assessment. Existing panels retain their last resolvable context.</div> : null}</div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><MetricCard label="Cryptographic assets" value={model.kpis.assets || "—"} note="Open active CBOM" icon={Boxes} onClick={() => routeInventory()} /><MetricCard label="Critical findings" value={model.kpis.critical || "—"} note="Filter critical evidence" icon={ShieldAlert} tone="rose" onClick={() => routeInventory("?risk=critical")} /><MetricCard label="High risk" value={model.kpis.high || "—"} note="Filter high evidence" icon={TriangleAlert} tone="amber" onClick={() => routeInventory("?risk=high")} /><MetricCard label="Quantum vulnerable" value={model.kpis.quantumVulnerable || "—"} note="View quantum exposure" icon={ScanSearch} tone="violet" onClick={() => routeInventory("?quantum=vulnerable")} /><MetricCard label="Potential HNDL" value={model.kpis.hndl || "—"} note="Open qualified findings" icon={LockKeyhole} tone="amber" onClick={() => routeInventory("?hndl=true")} /><MetricCard label="Quantum readiness" value={`${model.kpis.readiness || 0}%`} note="Review migration plan" icon={BookOpenCheck} tone="emerald" onClick={() => setLocation("/migration")} /></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><ChartHeading title="Risk distribution" description="Observed findings by current decision tier" badge={`${model.assessment.findings} total`} /><div className="mt-5"><RiskDistributionChart data={model.riskDistribution} onSelect={level => routeInventory(`?risk=${encodeURIComponent(level.toLowerCase())}`)} /></div></article><article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><ChartHeading title="Quantum exposure" description="Derived from observed finding states; not a readiness certification" /><div className="mt-5"><QuantumExposureChart data={model.quantumExposure} onSelectQuantum={() => routeInventory("?quantum=vulnerable")} /></div></article></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><ChartHeading title="Algorithm distribution" description="Top observed algorithms in the active evidence population" badge={`${model.algorithmDistribution.length} shown`} /><div className="mt-5"><AlgorithmDistribution data={model.algorithmDistribution} onSelect={algorithm => routeInventory(`?algorithm=${encodeURIComponent(algorithm)}`)} /></div></article><MigrationCandidates candidates={model.migrationCandidates} onSelect={findingKey => setLocation(`/migration?finding=${encodeURIComponent(findingKey)}`)} onViewAll={() => setLocation("/migration")} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">{isAuthenticated ? <RecentScans scans={model.recentScans} onNewScan={() => document.querySelector<HTMLInputElement>("[aria-label='Repository URL']")?.focus()} /> : <QuickActions onNewScan={() => document.querySelector<HTMLInputElement>("[aria-label='Repository URL']")?.focus()} onInventory={() => routeInventory()} onGuidance={() => setLocation("/migration")} />}<ActivityFeed items={model.activity} /></section>
  </div>;
}

function SummaryMetric({ value, label }: { value: number; label: string }) { return <div className="rounded-xl border border-white/[0.07] bg-[#06101c]/55 p-3"><p className="font-display text-lg font-semibold text-white">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p></div>; }
function ChartHeading({ title, description, badge }: { title: string; description: string; badge?: string }) { return <div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold tracking-[-0.03em] text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div>{badge ? <Badge variant="outline" className="border-white/10 text-slate-400">{badge}</Badge> : null}</div>; }
function MigrationCandidates({ candidates, onSelect, onViewAll }: { candidates: ReturnType<typeof buildCommandCenterViewModel>["migrationCandidates"]; onSelect: (findingKey: string) => void; onViewAll: () => void }) { return <article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><ChartHeading title="Top migration candidates" description="Quantum-vulnerable evidence ordered by generated priority, risk, and criticality" badge={`${candidates.length} shown`} />{candidates.length ? <div className="mt-5 space-y-2">{candidates.map(item => <button type="button" key={item.finding.findingKey} onClick={() => onSelect(item.finding.findingKey)} className="group flex w-full items-center justify-between gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-3 text-left transition hover:border-cyan-200/20 hover:bg-cyan-300/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60"><span className="min-w-0"><span className="flex items-center gap-2"><span className="rounded-md bg-rose-300/10 px-1.5 py-0.5 text-[10px] font-semibold text-rose-100">P{item.priority}</span><span className="truncate text-sm font-medium text-slate-100">{item.finding.algorithm}</span></span><span className="mt-1 block truncate text-xs text-slate-500">{item.finding.assetName} · {item.finding.library ?? "Library not observed"}</span></span><ArrowRight className="h-4 w-4 shrink-0 text-slate-600 transition group-hover:translate-x-0.5 group-hover:text-cyan-100" /></button>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No quantum-vulnerable findings with generated migration candidates are available in this assessment.</p>}<button type="button" onClick={onViewAll} className="mt-5 inline-flex items-center gap-2 text-xs font-medium text-cyan-100 hover:text-cyan-50">View all recommendations <ArrowRight className="h-3.5 w-3.5" /></button></article>; }
function RecentScans({ scans, onNewScan }: { scans: ReturnType<typeof buildCommandCenterViewModel>["recentScans"]; onNewScan: () => void }) { return <article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold tracking-[-0.03em] text-white">Recent scans</h2><p className="mt-1 text-xs leading-5 text-slate-500">Protected scan history available to this signed-in workspace.</p></div><Button size="sm" onClick={onNewScan} className="bg-cyan-200 text-[#072033] hover:bg-cyan-100">New scan</Button></div>{scans.length ? <div className="mt-5 overflow-hidden rounded-2xl border border-white/[0.07]"><div className="grid grid-cols-[minmax(0,1fr)_auto_auto] gap-3 border-b border-white/[0.07] px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-600"><span>Target</span><span>Assets</span><span>Status</span></div>{scans.map(scan => <div key={scan.scanKey} className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 px-3 py-3 text-xs"><span className="min-w-0"><span className="block truncate font-medium text-slate-200">{scan.displayName}</span><span className="mt-1 block text-[10px] text-slate-600">{new Date(scan.createdAt).toLocaleDateString()}</span></span><span className="text-slate-400">{scan.totalAssets}</span><span className="inline-flex items-center gap-1 text-emerald-100"><CheckCircle2 className="h-3.5 w-3.5" />{scan.status}</span></div>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No saved scans are available yet. Start a scenario above to create protected scan history.</p>}</article>; }
function QuickActions({ onNewScan, onInventory, onGuidance }: { onNewScan: () => void; onInventory: () => void; onGuidance: () => void }) { return <article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><h2 className="font-display text-xl font-semibold tracking-[-0.03em] text-white">Quick actions</h2><p className="mt-1 text-xs leading-5 text-slate-500">Explore the seeded evidence model or sign in to keep protected scan history.</p><div className="mt-5 grid gap-2 sm:grid-cols-3">{[["New discovery", onNewScan], ["Explore inventory", onInventory], ["Migration plan", onGuidance]].map(([label, action]) => <button type="button" key={String(label)} onClick={action as () => void} className="rounded-xl border border-white/[0.07] bg-white/[0.025] px-3 py-3 text-left text-xs font-medium text-slate-200 transition hover:border-cyan-200/20 hover:bg-cyan-300/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60">{String(label)}</button>)}</div></article>; }
function ActivityFeed({ items }: { items: ReturnType<typeof buildCommandCenterViewModel>["activity"] }) { const tone = { success: "bg-emerald-300", warning: "bg-amber-200", info: "bg-cyan-300" }; return <article className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-100"><Activity className="h-4 w-4" /></span><div><h2 className="font-display text-xl font-semibold tracking-[-0.03em] text-white">Recent activity</h2><p className="mt-0.5 text-xs text-slate-500">Active evidence context</p></div></div><div className="mt-5 space-y-4">{items.map(item => <div key={item.title} className="flex gap-3"><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${tone[item.type]}`} /><div><p className="text-sm font-medium text-slate-200">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p></div></div>)}</div></article>; }
