import { useAuth } from "@/_core/hooks/useAuth";
import { Breadcrumb, EcdatHeader } from "@/components/EcdatHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { downloadText } from "@/lib/ecdatUi";
import { trpc } from "@/lib/trpc";
import { Check, Download, FileCode2, FileJson2, FileText, LockKeyhole } from "lucide-react";

export default function Reports() { const { isAuthenticated } = useAuth(); const scans = trpc.ecdat.scans.useQuery(undefined, { enabled: isAuthenticated }); const scanKey = scans.data?.[0]?.scanKey; const exported = trpc.ecdat.export.useQuery({ scanKey: scanKey ?? "pending" }, { enabled: Boolean(scanKey) }); const locked = !isAuthenticated || !scanKey; return <div className="mx-auto max-w-[1550px]"><Breadcrumb section="Reports & export" /><EcdatHeader eyebrow="Portable evidence" title="Export the intelligence, not just a chart." description="Generate a CBOM-shaped JSON record or executive HTML summary once an authenticated user has saved a demo scan. Both preserve qualification notes and evidence context." /><div className="mt-7 grid gap-5 lg:grid-cols-2"><ExportCard icon={FileJson2} title="CBOM JSON" description="CycloneDX-oriented prototype export with asset properties, evidence, provenance, confidence, and risk context." locked={locked} actionLabel="Download JSON" onClick={() => exported.data && downloadText("ecdat-cbom.json", JSON.stringify(exported.data.cbom, null, 2), "application/json")} /><ExportCard icon={FileText} title="Executive HTML report" description="A concise decision document with posture metrics and an evidence-backed inventory table." locked={locked} actionLabel="Download HTML" onClick={() => exported.data && downloadText("ecdat-executive-report.html", exported.data.reportHtml, "text/html")} /></div><div className="mt-5 rounded-2xl border border-white/8 bg-[#091423] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-100"><FileCode2 className="h-5 w-5" /></span><div><p className="font-medium text-slate-100">Export readiness</p><p className="mt-1 text-xs leading-5 text-slate-500">Saved scans are retained per authenticated user. The export labels this build as a CBOM-oriented prototype and asks teams to validate the target schema before production use.</p></div></div>{locked ? <Button onClick={() => startLogin()} className="bg-cyan-200 text-[#072033] hover:bg-cyan-100"><LockKeyhole className="h-4 w-4" />Sign in and save a scan</Button> : <Badge variant="outline" className="w-fit border-emerald-200/20 bg-emerald-300/[0.04] text-emerald-100"><Check className="mr-1.5 h-3.5 w-3.5" />Ready from saved scan</Badge>}</div></div></div>; }
function ExportCard({ icon: Icon, title, description, locked, actionLabel, onClick }: { icon: typeof FileJson2; title: string; description: string; locked: boolean; actionLabel: string; onClick: () => void }) { return <article className="rounded-3xl border border-white/8 bg-[#091423] p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-100"><Icon className="h-5 w-5" /></span><h2 className="mt-5 font-display text-xl font-semibold text-white">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-400">{description}</p><Button onClick={onClick} disabled={locked} className="mt-6 bg-white/8 text-slate-100 hover:bg-white/12 disabled:opacity-45"><Download className="h-4 w-4" />{actionLabel}</Button></article>; }
